title: StarSquare Designs
description: Bringing your great ideas to life.
url: https://starsquare.co.uk
permalink: /:title/
defaults:
- values:
    layout: default
plugins:
- jekyll-titles-from-headings
titles_from_headings:
  enabled: true
